@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "com.brh.marsroverdownloader.Controller",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_97816 { 
   	label=brh
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_209535920 { 
   	label=marsroverdownloader
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   APIRequest1796587965[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)APIRequest</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   apiKey: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   onSuccessCallback: Consumer&lt;ArrayList&lt;MarsRoverImage&gt;&gt; [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ getRoverImageByDate(date: LocalDate, onSuccessCallback: Consumer&lt;ArrayList&lt;MarsRoverImage&gt;&gt;)</TD></TR>
<TR><TD ALIGN="LEFT" >- handleApiResponse(response: HttpResponse&lt;String&gt;)</TD></TR>
<TR><TD ALIGN="LEFT" >- parseJson(json: String): ArrayList&lt;MarsRoverImage&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >- sendRequest(date: LocalDate)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Controller1796587965[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Controller</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   cameraCol: TableColumn&lt;MarsRoverImage, String&gt; [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   dateCol: TableColumn&lt;MarsRoverImage, LocalDate&gt; [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   datePicker: DatePicker [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   imageList: ObservableList&lt;MarsRoverImage&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   progressCol: TableColumn&lt;MarsRoverImage, Integer&gt; [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   tableView: TableView&lt;MarsRoverImage&gt; [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   targetFolder: Label [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   urlCol: TableColumn&lt;MarsRoverImage, String&gt; [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ getImageFromAPI()</TD></TR>
<TR><TD ALIGN="LEFT" >+ handleRoverImages(response: ArrayList&lt;MarsRoverImage&gt;)</TD></TR>
<TR><TD ALIGN="LEFT" >+ initialize()</TD></TR>
<TR><TD ALIGN="LEFT" ># searchTargetFolder(ev: Event)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

MarsRoverImage1796587965[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)MarsRoverImage</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   cameraName: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   date: LocalDate [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   downloadProgress: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   imgURL: String [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 
} 

'edges    
APIRequest1796587965 -> MarsRoverImage1796587965[label="onSuccessCallback
[0..1]"];
Controller1796587965 -> APIRequest1796587965[label="getImageFromAPI() -> getRoverImageByDate()"];
Controller1796587965 -> MarsRoverImage1796587965[label="cameraCol
[0..1]"];
Controller1796587965 -> MarsRoverImage1796587965[label="dateCol
[0..1]"];
Controller1796587965 -> MarsRoverImage1796587965[label="imageList
[0..*]"];
Controller1796587965 -> MarsRoverImage1796587965[label="progressCol
[0..1]"];
Controller1796587965 -> MarsRoverImage1796587965[label="tableView
[0..1]"];
Controller1796587965 -> MarsRoverImage1796587965[label="urlCol
[0..1]"];
    
}
@enduml